### model
#model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
#model_name_or_path: /project/models/HF/meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: /scratch/common_models/Llama-3.2-3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_dropout: 0.1

### dataset
dataset: pddl_orig_test
template: llama3
cutoff_len: 4096
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
train_on_prompt: false

### output
output_dir: saves/llama3-8b/lora/original/template
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 50
lr_scheduler_type: cosine
warmup_ratio: 0
bf16: true
ddp_timeout: 180000000

### eval
#do_eval: true
#val_size: 0.1
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 500

#if you want to save best model:
#evaluation_strategy: steps
#save_strategy: steps
#save_total_limit: 1
#load_best_model_at_end: True
#metric_for_best_model: "eval_loss"
#greater_is_better: False  # Lower eval_loss is better

